services:
  my-web:
    image: gori/simple-apps
    build: ./app
    ports:
      - 3000:3000
    volumes:
      - vol-simple-apps:/app 

phpmyadmin:
  image: phpmyadmin
  restart: always
  ports:
   -0890:80
  environment:
    - PMA_HOST=172.17.0.1

volumes:
  vol-simple-apps: {}
